// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pagsftohiyyuclqywcad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhZ3NmdG9oaXl5dWNscXl3Y2FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTE1MjcsImV4cCI6MjA3MDEyNzUyN30.NNg03_H2DYyto51rG8IxMe0IC5sFMWhwoRAmboCp75s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});